### PR TITLE
Adding working Linux x86_64 and Linux x86_32 platform

### PR DESCRIPTION
**Pull request by fjpavm**
Added Linux platform to ChilliSource following the Windows version SFML based implementation but with Makefile project files.
Known short comings are:
- Dialog Box system is simply printing to stdout and auto accepting.
- Linux x86_64 and x86_32 targets have full libraries but should not be hard to add arm support if underlying libraries support it.

Tested on and finalised along linux version of CSSamples and CSTest that can be merged soon after. Passed all regular tests. Dialog Box smoke tests of course simply printed to console.

### CODE REVIEW

**Comment by fjpavm** [comment]
Project completely inactive :( Closed pull request but may continue to develop in my own branch in future if there is interest.

**Comment by snik0** [comment]
Hey fjpavm, you can try contacting https://github.com/ScottDownie-Tag, I'm not sure what the current project status is.
@fjpavm

**Comment by fjpavm** [comment]
> Hey fjpavm, you can try contacting https://github.com/ScottDownie-Tag, I'm not sure what the current project status is. @fjpavm

I'm not sure any of the Tag github accounts are still active since Tag Games got bought by Scoply (their email addresses probably changed). Guess I can try him on LinkedIn. Mostly did this to prove to myself I could stll handle a non academic coding project.

**Comment by snik0** [comment]
It's nice work.

**Pull request closed without merging**
